# =============== Mail Services ===============

# Add your mails services here. There are default mails services.

Gmail:
  name: gmail
  smtp_address: smtp.gmail.com
  smtp_port: 587
  imap_address: imap.gmail.com
  imap_port: 993
  
Yahoo:
  name: yahoo
  smtp_address: smtp.mail.yahoo.com
  smtp_port: 587
  imap_address: imap.mail.yahoo.com
  imap_port: 993
  starttls: true
  
Outlook:
  name: outlook
  smtp_address: smtp.office365.com
  smtp_port: 587
  imap_address: outlook.office365.com
  imap_port: 993
  starttls: true
  
Zoho:
  name: zoho
  smtp_address: smtp.zoho.com
  smtp_port: 587
  imap_address: imap.zoho.com
  imap_port: 993
  starttls: true
  
GMX:
  name: gmx
  smtp_address: mail.gmx.com
  smtp_port: 587
  imap_address: imap.gmx.com
  imap_port: 993
  starttls: true
  
NTL:
  name: ntl
  smtp_address: smtp.ntlworld.com
  smtp_port: 587
  imap_address: imap.ntlworld.com
  imap_port: 993
  starttls: true
  
AOL:
  name: aol
  smtp_address: smtp.aol.com
  smtp_port: 587
  imap_address: imap.aol.com
  imap_port: 993
  starttls: true
